[2024-01-28T09:21:00.925+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T09:21:00.938+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T09:21:00.939+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-28T09:21:00.979+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-27 00:00:00+00:00
[2024-01-28T09:21:00.990+0100] {standard_task_runner.py:60} INFO - Started process 9339 to run task
[2024-01-28T09:21:00.997+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmp1csr8e1_']
[2024-01-28T09:21:01.000+0100] {standard_task_runner.py:88} INFO - Job 57: Subtask submit_spark_job
[2024-01-28T09:21:01.067+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T09:21:01.148+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T09:21:01.155+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-28T09:21:01.157+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-28T09:21:04.373+0100] {spark_submit.py:571} INFO - 24/01/28 09:21:04 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-28T09:21:04.385+0100] {spark_submit.py:571} INFO - 24/01/28 09:21:04 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-28T09:21:04.496+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-28T09:21:04.498+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-28T09:21:04.500+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-28T09:21:04.501+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-28T09:21:04.502+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-28T09:21:04.503+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-01-28T09:21:04.503+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-01-28T09:21:04.504+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-28T09:21:04.505+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-28T09:21:04.505+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-28T09:21:04.506+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-28T09:21:04.537+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-28T09:21:04.543+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240127T000000, start_date=20240128T082100, end_date=20240128T082104
[2024-01-28T09:21:04.584+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task submit_spark_job (Cannot execute: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 9339)
[2024-01-28T09:21:04.638+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-28T09:21:04.675+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-28T10:55:13.473+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T10:55:13.491+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T10:55:13.492+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-28T10:55:13.584+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-27 00:00:00+00:00
[2024-01-28T10:55:13.604+0100] {standard_task_runner.py:60} INFO - Started process 17295 to run task
[2024-01-28T10:55:13.635+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmpqu3t2f9t']
[2024-01-28T10:55:13.643+0100] {standard_task_runner.py:88} INFO - Job 49: Subtask submit_spark_job
[2024-01-28T10:55:13.868+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T10:55:14.216+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T10:55:14.254+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-28T10:55:14.265+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-28T10:55:34.511+0100] {spark_submit.py:571} INFO - 24/01/28 10:55:34 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-28T10:55:34.521+0100] {spark_submit.py:571} INFO - 24/01/28 10:55:34 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-28T10:55:34.955+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-28T10:55:34.959+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-28T10:55:34.960+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-28T10:55:34.960+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-28T10:55:34.960+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-28T10:55:34.960+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-01-28T10:55:34.961+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-01-28T10:55:34.961+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-28T10:55:34.962+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-28T10:55:34.969+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-28T10:55:34.969+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-28T10:55:35.112+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-28T10:55:35.245+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240127T000000, start_date=20240128T095513, end_date=20240128T095535
[2024-01-28T10:55:35.414+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task submit_spark_job (Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 17295)
[2024-01-28T10:55:35.543+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-28T10:55:35.592+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
