[2024-01-28T09:26:09.153+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T09:26:09.164+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T09:26:09.167+0100] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-28T09:26:09.202+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-27 00:00:00+00:00
[2024-01-28T09:26:09.211+0100] {standard_task_runner.py:60} INFO - Started process 9703 to run task
[2024-01-28T09:26:09.216+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmpvxfsi63z']
[2024-01-28T09:26:09.220+0100] {standard_task_runner.py:88} INFO - Job 58: Subtask submit_spark_job
[2024-01-28T09:26:09.296+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T09:26:09.389+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T09:26:09.398+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-28T09:26:09.401+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-28T09:26:12.527+0100] {spark_submit.py:571} INFO - 24/01/28 09:26:12 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-28T09:26:12.535+0100] {spark_submit.py:571} INFO - 24/01/28 09:26:12 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-28T09:26:12.627+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-28T09:26:12.628+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-28T09:26:12.628+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-28T09:26:12.629+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-28T09:26:12.630+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-28T09:26:12.630+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-01-28T09:26:12.631+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-01-28T09:26:12.631+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-28T09:26:12.632+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-28T09:26:12.632+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-28T09:26:12.633+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-28T09:26:12.681+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-28T09:26:12.685+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240127T000000, start_date=20240128T082609, end_date=20240128T082612
[2024-01-28T09:26:12.717+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task submit_spark_job (Cannot execute: spark-submit --master yarn --name your_spark_job --queue root.default hdfs:///user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 9703)
[2024-01-28T09:26:12.752+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-28T09:26:12.785+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-28T11:00:40.286+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T11:00:40.352+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T11:00:40.367+0100] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-28T11:00:40.440+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-27 00:00:00+00:00
[2024-01-28T11:00:40.485+0100] {standard_task_runner.py:60} INFO - Started process 17577 to run task
[2024-01-28T11:00:40.493+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmp7nr7z9_h']
[2024-01-28T11:00:40.498+0100] {standard_task_runner.py:88} INFO - Job 51: Subtask submit_spark_job
[2024-01-28T11:00:40.582+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job scheduled__2024-01-27T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T11:00:40.675+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T11:00:40.685+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-28T11:00:40.687+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-28T11:00:46.084+0100] {spark_submit.py:571} INFO - 24/01/28 11:00:46 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-28T11:00:46.091+0100] {spark_submit.py:571} INFO - 24/01/28 11:00:46 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-28T11:00:46.219+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-28T11:00:46.220+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-28T11:00:46.220+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-28T11:00:46.221+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-28T11:00:46.222+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-28T11:00:46.223+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-01-28T11:00:46.223+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-01-28T11:00:46.224+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-28T11:00:46.224+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-28T11:00:46.225+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-28T11:00:46.225+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-28T11:00:46.354+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-28T11:00:46.360+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240127T000000, start_date=20240128T100040, end_date=20240128T100046
[2024-01-28T11:00:46.528+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task submit_spark_job (Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default hdfs://user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 17577)
[2024-01-28T11:00:46.604+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-28T11:00:46.651+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
