[2024-01-20T18:00:08.164+0100] {processor.py:161} INFO - Started process (PID=24052) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:00:08.188+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:00:08.347+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:00:08.238+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:00:10.604+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:00:10.286+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:00:10.610+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:00:11.786+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 3.723 seconds
[2024-01-20T18:03:05.190+0100] {processor.py:161} INFO - Started process (PID=24161) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:03:05.234+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:03:05.248+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:03:05.241+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:03:05.616+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:03:05.585+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:03:05.624+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:03:05.765+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.628 seconds
[2024-01-20T18:05:23.997+0100] {processor.py:161} INFO - Started process (PID=24229) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:05:24.006+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:05:24.014+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:05:24.013+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:05:24.051+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:05:24.042+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:05:24.053+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:05:24.140+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.151 seconds
[2024-01-20T18:07:04.514+0100] {processor.py:161} INFO - Started process (PID=24278) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:07:04.525+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:07:04.529+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:07:04.527+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:07:04.573+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:07:04.571+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:07:04.574+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:07:04.786+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.287 seconds
[2024-01-20T18:09:48.237+0100] {processor.py:161} INFO - Started process (PID=24443) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:09:48.247+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:09:48.250+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:09:48.249+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:09:48.296+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:09:48.284+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:09:48.302+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:09:48.462+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.249 seconds
[2024-01-20T18:11:39.885+0100] {processor.py:161} INFO - Started process (PID=24619) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:11:39.889+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:11:39.895+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:11:39.892+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:11:39.940+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:11:39.931+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:11:39.941+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:11:40.007+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.135 seconds
[2024-01-20T18:12:43.708+0100] {processor.py:161} INFO - Started process (PID=24667) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:12:43.716+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:12:43.719+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:12:43.718+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:12:43.777+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:12:43.766+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:12:43.778+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:12:43.873+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.182 seconds
[2024-01-20T18:13:50.656+0100] {processor.py:161} INFO - Started process (PID=24731) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:13:50.671+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:13:50.677+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:13:50.676+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:13:50.723+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:13:50.714+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:13:50.724+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:13:50.773+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.127 seconds
[2024-01-20T18:14:38.206+0100] {processor.py:161} INFO - Started process (PID=24777) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:14:38.222+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:14:38.225+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:14:38.223+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:14:38.254+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:14:38.252+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:14:38.255+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:14:38.296+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.121 seconds
[2024-01-20T18:15:37.728+0100] {processor.py:161} INFO - Started process (PID=24924) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:15:37.736+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:15:37.745+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:15:37.744+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:15:37.829+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:15:37.816+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:15:37.834+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:15:37.966+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.247 seconds
[2024-01-20T18:16:47.768+0100] {processor.py:161} INFO - Started process (PID=25048) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:16:47.771+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:16:47.774+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:16:47.773+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:16:47.846+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:16:47.820+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:16:47.864+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:16:47.982+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.222 seconds
[2024-01-20T18:17:28.656+0100] {processor.py:161} INFO - Started process (PID=25087) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:17:28.664+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:17:28.669+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:17:28.667+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:17:28.716+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:17:28.711+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:17:28.717+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:17:28.761+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.112 seconds
[2024-01-20T18:18:08.877+0100] {processor.py:161} INFO - Started process (PID=25122) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:08.882+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:18:08.885+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:18:08.884+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:08.921+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:18:08.919+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:18:08.923+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:08.968+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.110 seconds
[2024-01-20T18:18:47.624+0100] {processor.py:161} INFO - Started process (PID=25168) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:47.630+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:18:47.635+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:18:47.632+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:47.674+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:18:47.669+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:18:47.676+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:18:47.756+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.142 seconds
[2024-01-20T18:19:24.531+0100] {processor.py:161} INFO - Started process (PID=25203) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:19:24.534+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:19:24.536+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:19:24.535+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:19:24.558+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:19:24.557+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:19:24.560+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:19:24.605+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.080 seconds
[2024-01-20T18:20:05.883+0100] {processor.py:161} INFO - Started process (PID=25236) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:05.892+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:20:05.895+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:20:05.894+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:05.925+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:20:05.916+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:20:05.926+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:05.967+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.092 seconds
[2024-01-20T18:20:57.690+0100] {processor.py:161} INFO - Started process (PID=25326) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:57.695+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:20:57.697+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:20:57.696+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:57.732+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:20:57.725+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:20:57.734+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:20:57.787+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.103 seconds
[2024-01-20T18:21:54.204+0100] {processor.py:161} INFO - Started process (PID=25371) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:21:54.210+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:21:54.214+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:21:54.212+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:21:54.259+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:21:54.251+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:21:54.260+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:21:54.321+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.130 seconds
[2024-01-20T18:22:48.873+0100] {processor.py:161} INFO - Started process (PID=25412) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:22:48.878+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:22:48.881+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:22:48.880+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:22:48.912+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:22:48.904+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:22:48.914+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:22:48.958+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.092 seconds
[2024-01-20T18:23:46.432+0100] {processor.py:161} INFO - Started process (PID=25505) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:23:46.441+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:23:46.444+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:23:46.443+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:23:46.482+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:23:46.476+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:23:46.484+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:23:46.567+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.143 seconds
[2024-01-20T18:25:01.320+0100] {processor.py:161} INFO - Started process (PID=25948) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:01.326+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:25:01.328+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:25:01.328+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:01.356+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:25:01.351+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:25:01.356+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:01.395+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.082 seconds
[2024-01-20T18:25:58.135+0100] {processor.py:161} INFO - Started process (PID=25999) to work on /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:58.142+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/lib/my_dag.py for tasks to queue
[2024-01-20T18:25:58.145+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:25:58.144+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:58.184+0100] {logging_mixin.py:188} INFO - [2024-01-20T18:25:58.176+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/lib/my_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 52, in <module>
    find_popular_movies_and_save()
  File "/home/ubuntu/airflow/dags/lib/my_dag.py", line 36, in find_popular_movies_and_save
    response = requests.get(base_url, params=params)
NameError: name 'requests' is not defined
[2024-01-20T18:25:58.186+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/lib/my_dag.py
[2024-01-20T18:25:58.247+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/lib/my_dag.py took 0.125 seconds
