[2024-01-26T20:12:46.235+0100] {processor.py:161} INFO - Started process (PID=18191) to work on /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:12:46.238+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/hdfsDag.py for tasks to queue
[2024-01-26T20:12:46.239+0100] {logging_mixin.py:188} INFO - [2024-01-26T20:12:46.239+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:12:46.385+0100] {logging_mixin.py:188} INFO - [2024-01-26T20:12:46.363+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/hdfsDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/hdfsDag.py", line 5, in <module>
    from airflow.contrib.operators.spark_submit_operator import SparkSubmitOperator
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.providers.apache.spark.operators.spark_submit.SparkSubmitOperator` while trying to import `airflow.contrib.operators.spark_submit_operator.SparkSubmitOperator`.
[2024-01-26T20:12:46.390+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:12:46.465+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/hdfsDag.py took 0.276 seconds
[2024-01-26T20:16:56.089+0100] {processor.py:161} INFO - Started process (PID=18337) to work on /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:16:56.092+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/hdfsDag.py for tasks to queue
[2024-01-26T20:16:56.098+0100] {logging_mixin.py:188} INFO - [2024-01-26T20:16:56.095+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:16:56.181+0100] {logging_mixin.py:188} INFO - [2024-01-26T20:16:56.162+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/hdfsDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/hdfsDag.py", line 5, in <module>
    from airflow.contrib.operators.spark_submit_operator import SparkSubmitOperator
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.providers.apache.spark.operators.spark_submit.SparkSubmitOperator` while trying to import `airflow.contrib.operators.spark_submit_operator.SparkSubmitOperator`.
[2024-01-26T20:16:56.182+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/hdfsDag.py
[2024-01-26T20:16:56.317+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/hdfsDag.py took 0.243 seconds
